spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_bank_deal_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081

credit-bank:
  services:
    calculator:
      base:
        uri: http://localhost:8080