spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_bank_deal_db
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  port: 8081

feign:
  client:
    config:
      calculator:
        name: calculator-client
        url: http://localhost:8080/calculator